version: 2
updates:
- package-ecosystem: cargo
  directory: "/submission-system"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: git2
    versions:
    - 0.13.17
