[package]
name = "submission-system"
version = "0.1.0"
authors = ["Skgland <bb-github@t-online.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.114", features=["derive"]}
ron = "0.6.0"
git2 = "0.13.6"
tempdir = "0.3.7"

